# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_warp_cli_global_optspecs
	string join \n l/listen t/timeout= accept-tos v/verbose j/json no-paginate no-ansi h/help V/version
end

function __fish_warp_cli_needs_command
	# Figure out if the current invocation already has a command.
	set -l cmd (commandline -opc)
	set -e cmd[1]
	argparse -s (__fish_warp_cli_global_optspecs) -- $cmd 2>/dev/null
	or return
	if set -q argv[1]
		# Also print the command, so this can be used to figure out what it is.
		echo $argv[1]
		return 1
	end
	return 0
end

function __fish_warp_cli_using_subcommand
	set -l cmd (__fish_warp_cli_needs_command)
	test -z "$cmd"
	and return 1
	contains -- $cmd[1] $argv
end

complete -c warp-cli -n "__fish_warp_cli_needs_command" -s t -l timeout -d 'Timeout (in seconds) before IPC channel is considered hung' -r
complete -c warp-cli -n "__fish_warp_cli_needs_command" -s l -l listen -d 'Listen for status changes and DNS logs (if enabled)'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -l accept-tos -d 'Accept the Terms of Service agreement'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -s v -l verbose -d 'Enable verbose output. Multiple "v"s adds more verbosity'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -s j -l json -d 'Pretty print output as json'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -l no-ansi -d 'Disable ANSI characters in standard outputs'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -s V -l version -d 'Print version'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -f -a "api" -d 'Allow overriding Cloudflare API address'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -f -a "connect" -d 'Maintain a connection whenever possible'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -f -a "debug" -d 'Debugging commands'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -f -a "disconnect" -d 'Disconnect the client'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -f -a "dns" -d 'Configure DNS settings'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -f -a "mdm" -d 'MDM configs'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -f -a "mode" -d 'Set the client\'s general operating mode'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -f -a "override" -d 'Allow temporary overrides of administrative settings'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -f -a "proxy" -d 'Configure proxy mode settings'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -f -a "registration" -d 'Registration settings'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -f -a "connector" -d 'Register a WARP Connector'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -f -a "settings" -d 'Show or alter general application settings'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -f -a "status" -d 'Return the current connection status'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -f -a "target" -d 'Manage targets'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -f -a "trusted" -d 'Configure trusted networks where the client will be automatically disabled (Consumer only)'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -f -a "tunnel" -d 'Configure tunnel settings'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -f -a "vnet" -d 'Get or specify connected virtual network'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -f -a "generate-completions" -d 'Generate completions for a given shell and print to stdout'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -f -a "stats" -d 'Display statistics for Cloudflare WARP'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -f -a "certs" -d 'Print all account certificates installed on the device to stdout'
complete -c warp-cli -n "__fish_warp_cli_needs_command" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand api; and not __fish_seen_subcommand_from endpoint help" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand api; and not __fish_seen_subcommand_from endpoint help" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand api; and not __fish_seen_subcommand_from endpoint help" -f -a "endpoint" -d 'Set an override endpoint for the WARP API'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand api; and not __fish_seen_subcommand_from endpoint help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand api; and __fish_seen_subcommand_from endpoint" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand api; and __fish_seen_subcommand_from endpoint" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand api; and __fish_seen_subcommand_from endpoint" -f -a "set" -d 'Set an override IP to use for the Cloudflare API IP'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand api; and __fish_seen_subcommand_from endpoint" -f -a "reset" -d 'Remove any configured override IP for the Cloudflare API'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand api; and __fish_seen_subcommand_from endpoint" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand api; and __fish_seen_subcommand_from help" -f -a "endpoint" -d 'Set an override endpoint for the WARP API'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand api; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand connect" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand connect" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and not __fish_seen_subcommand_from access-reauth alternate-network connectivity-check dex network panic posture pcap task-dump qlog log-filter help" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and not __fish_seen_subcommand_from access-reauth alternate-network connectivity-check dex network panic posture pcap task-dump qlog log-filter help" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and not __fish_seen_subcommand_from access-reauth alternate-network connectivity-check dex network panic posture pcap task-dump qlog log-filter help" -f -a "access-reauth" -d 'Force refresh authentication with Cloudflare Access'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and not __fish_seen_subcommand_from access-reauth alternate-network connectivity-check dex network panic posture pcap task-dump qlog log-filter help" -f -a "alternate-network" -d 'Get the name of the currently detected alternate network, if any'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and not __fish_seen_subcommand_from access-reauth alternate-network connectivity-check dex network panic posture pcap task-dump qlog log-filter help" -f -a "connectivity-check" -d 'Enable or disable connectivity checks'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and not __fish_seen_subcommand_from access-reauth alternate-network connectivity-check dex network panic posture pcap task-dump qlog log-filter help" -f -a "dex" -d 'Get the most recently uploaded DEX data. Returns the most recent test for each dex metric'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and not __fish_seen_subcommand_from access-reauth alternate-network connectivity-check dex network panic posture pcap task-dump qlog log-filter help" -f -a "network" -d 'Display the current network information'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and not __fish_seen_subcommand_from access-reauth alternate-network connectivity-check dex network panic posture pcap task-dump qlog log-filter help" -f -a "panic" -d 'Force a daemon panic'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and not __fish_seen_subcommand_from access-reauth alternate-network connectivity-check dex network panic posture pcap task-dump qlog log-filter help" -f -a "posture" -d 'Display the most recent device posture information'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and not __fish_seen_subcommand_from access-reauth alternate-network connectivity-check dex network panic posture pcap task-dump qlog log-filter help" -f -a "pcap" -d 'Run a packet capture on the device'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and not __fish_seen_subcommand_from access-reauth alternate-network connectivity-check dex network panic posture pcap task-dump qlog log-filter help" -f -a "task-dump" -d 'Get a dump of the currently running async tasks'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and not __fish_seen_subcommand_from access-reauth alternate-network connectivity-check dex network panic posture pcap task-dump qlog log-filter help" -f -a "qlog" -d 'Enable qlog logging on the tunnel, if supported by the tunnel protocol'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and not __fish_seen_subcommand_from access-reauth alternate-network connectivity-check dex network panic posture pcap task-dump qlog log-filter help" -f -a "log-filter" -d 'Modify the dynamic log filter using env-filter directives'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and not __fish_seen_subcommand_from access-reauth alternate-network connectivity-check dex network panic posture pcap task-dump qlog log-filter help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from access-reauth" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from access-reauth" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from alternate-network" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from alternate-network" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from connectivity-check" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from connectivity-check" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from dex" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from dex" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from network" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from network" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from panic" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from panic" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from posture" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from posture" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from pcap" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from pcap" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from pcap" -f -a "start" -d 'Start packet capture'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from pcap" -f -a "stop" -d 'Stop packet capture'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from pcap" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from task-dump" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from task-dump" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from qlog" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from qlog" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from log-filter" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from log-filter" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from log-filter" -f -a "set" -d 'Set the dynamic log filter'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from log-filter" -f -a "reset" -d 'Reset the dynamic log filter'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from log-filter" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from help" -f -a "access-reauth" -d 'Force refresh authentication with Cloudflare Access'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from help" -f -a "alternate-network" -d 'Get the name of the currently detected alternate network, if any'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from help" -f -a "connectivity-check" -d 'Enable or disable connectivity checks'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from help" -f -a "dex" -d 'Get the most recently uploaded DEX data. Returns the most recent test for each dex metric'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from help" -f -a "network" -d 'Display the current network information'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from help" -f -a "panic" -d 'Force a daemon panic'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from help" -f -a "posture" -d 'Display the most recent device posture information'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from help" -f -a "pcap" -d 'Run a packet capture on the device'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from help" -f -a "task-dump" -d 'Get a dump of the currently running async tasks'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from help" -f -a "qlog" -d 'Enable qlog logging on the tunnel, if supported by the tunnel protocol'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from help" -f -a "log-filter" -d 'Modify the dynamic log filter using env-filter directives'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand debug; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand disconnect" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand disconnect" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and not __fish_seen_subcommand_from endpoint fallback families gateway-id log stats default-fallbacks help" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and not __fish_seen_subcommand_from endpoint fallback families gateway-id log stats default-fallbacks help" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and not __fish_seen_subcommand_from endpoint fallback families gateway-id log stats default-fallbacks help" -f -a "endpoint" -d 'Configure a custom DNS Over HTTPS server endpoint'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and not __fish_seen_subcommand_from endpoint fallback families gateway-id log stats default-fallbacks help" -f -a "fallback" -d 'Configure fallback domains'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and not __fish_seen_subcommand_from endpoint fallback families gateway-id log stats default-fallbacks help" -f -a "families" -d 'Configure Families Mode settings (Consumer only)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and not __fish_seen_subcommand_from endpoint fallback families gateway-id log stats default-fallbacks help" -f -a "gateway-id" -d 'Force the app to use the specified Gateway ID for DNS queries'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and not __fish_seen_subcommand_from endpoint fallback families gateway-id log stats default-fallbacks help" -f -a "log" -d 'Enable/Disable DNS logging'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and not __fish_seen_subcommand_from endpoint fallback families gateway-id log stats default-fallbacks help" -f -a "stats" -d 'Retrieve DNS stats for the current connection'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and not __fish_seen_subcommand_from endpoint fallback families gateway-id log stats default-fallbacks help" -f -a "default-fallbacks" -d 'Display which DNS servers are being used for default fallback'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and not __fish_seen_subcommand_from endpoint fallback families gateway-id log stats default-fallbacks help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from endpoint" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from endpoint" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from endpoint" -f -a "set" -d 'Set an override IP to use for the Cloudflare API IP'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from endpoint" -f -a "reset" -d 'Remove any configured override IP for the Cloudflare API'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from endpoint" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from fallback" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from fallback" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from fallback" -f -a "list"
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from fallback" -f -a "add"
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from fallback" -f -a "remove"
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from fallback" -f -a "reset"
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from fallback" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from families" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from families" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from gateway-id" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from gateway-id" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from gateway-id" -f -a "set" -d 'Set an override'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from gateway-id" -f -a "reset" -d 'Remove any configured override'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from gateway-id" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from log" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from log" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from stats" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from stats" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from default-fallbacks" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from default-fallbacks" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from help" -f -a "endpoint" -d 'Configure a custom DNS Over HTTPS server endpoint'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from help" -f -a "fallback" -d 'Configure fallback domains'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from help" -f -a "families" -d 'Configure Families Mode settings (Consumer only)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from help" -f -a "gateway-id" -d 'Force the app to use the specified Gateway ID for DNS queries'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from help" -f -a "log" -d 'Enable/Disable DNS logging'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from help" -f -a "stats" -d 'Retrieve DNS stats for the current connection'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from help" -f -a "default-fallbacks" -d 'Display which DNS servers are being used for default fallback'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand dns; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand mdm; and not __fish_seen_subcommand_from get-configs set-config help" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand mdm; and not __fish_seen_subcommand_from get-configs set-config help" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand mdm; and not __fish_seen_subcommand_from get-configs set-config help" -f -a "get-configs" -d 'Show information about current MDM configurations'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand mdm; and not __fish_seen_subcommand_from get-configs set-config help" -f -a "set-config" -d 'Apply config from configs found in MDM file'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand mdm; and not __fish_seen_subcommand_from get-configs set-config help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand mdm; and __fish_seen_subcommand_from get-configs" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand mdm; and __fish_seen_subcommand_from get-configs" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand mdm; and __fish_seen_subcommand_from set-config" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand mdm; and __fish_seen_subcommand_from set-config" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand mdm; and __fish_seen_subcommand_from help" -f -a "get-configs" -d 'Show information about current MDM configurations'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand mdm; and __fish_seen_subcommand_from help" -f -a "set-config" -d 'Apply config from configs found in MDM file'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand mdm; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand mode" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand mode" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand override; and not __fish_seen_subcommand_from show unlock generate local-network help" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand override; and not __fish_seen_subcommand_from show unlock generate local-network help" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand override; and not __fish_seen_subcommand_from show unlock generate local-network help" -a "show" -d 'Return information about any currently applied administrative override'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand override; and not __fish_seen_subcommand_from show unlock generate local-network help" -a "unlock" -d 'Temporarily override policies that require the client to stay enabled'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand override; and not __fish_seen_subcommand_from show unlock generate local-network help" -a "generate" -d 'Generate admin override code for Teams account (requires admin permissions)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand override; and not __fish_seen_subcommand_from show unlock generate local-network help" -a "local-network" -d 'Override settings to access the local area network'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand override; and not __fish_seen_subcommand_from show unlock generate local-network help" -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand override; and __fish_seen_subcommand_from show" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand override; and __fish_seen_subcommand_from show" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand override; and __fish_seen_subcommand_from unlock" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand override; and __fish_seen_subcommand_from unlock" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand override; and __fish_seen_subcommand_from generate" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand override; and __fish_seen_subcommand_from generate" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand override; and __fish_seen_subcommand_from local-network" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand override; and __fish_seen_subcommand_from local-network" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand override; and __fish_seen_subcommand_from local-network" -f -a "allow" -d 'Allow access to the local network, if permitted by settings'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand override; and __fish_seen_subcommand_from local-network" -f -a "show" -d 'Return information about any currently applied local network access'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand override; and __fish_seen_subcommand_from local-network" -f -a "stop" -d 'Stop any current local network access'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand override; and __fish_seen_subcommand_from local-network" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand override; and __fish_seen_subcommand_from help" -f -a "show" -d 'Return information about any currently applied administrative override'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand override; and __fish_seen_subcommand_from help" -f -a "unlock" -d 'Temporarily override policies that require the client to stay enabled'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand override; and __fish_seen_subcommand_from help" -f -a "generate" -d 'Generate admin override code for Teams account (requires admin permissions)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand override; and __fish_seen_subcommand_from help" -f -a "local-network" -d 'Override settings to access the local area network'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand override; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand proxy; and not __fish_seen_subcommand_from port help" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand proxy; and not __fish_seen_subcommand_from port help" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand proxy; and not __fish_seen_subcommand_from port help" -f -a "port" -d 'Override the listening port for proxy mode (127.0.0.1:{port})'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand proxy; and not __fish_seen_subcommand_from port help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand proxy; and __fish_seen_subcommand_from port" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand proxy; and __fish_seen_subcommand_from port" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand proxy; and __fish_seen_subcommand_from help" -f -a "port" -d 'Override the listening port for proxy mode (127.0.0.1:{port})'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand proxy; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and not __fish_seen_subcommand_from show new delete organization devices license token initialize-token-callback help" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and not __fish_seen_subcommand_from show new delete organization devices license token initialize-token-callback help" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and not __fish_seen_subcommand_from show new delete organization devices license token initialize-token-callback help" -f -a "show" -d 'Show information about the current registration'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and not __fish_seen_subcommand_from show new delete organization devices license token initialize-token-callback help" -f -a "new" -d 'Register this client (Must be run before first connection!)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and not __fish_seen_subcommand_from show new delete organization devices license token initialize-token-callback help" -f -a "delete" -d 'Delete current registration'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and not __fish_seen_subcommand_from show new delete organization devices license token initialize-token-callback help" -f -a "organization" -d 'Get the name of the current Teams organization'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and not __fish_seen_subcommand_from show new delete organization devices license token initialize-token-callback help" -f -a "devices" -d 'Display the list of devices associated with the current registration'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and not __fish_seen_subcommand_from show new delete organization devices license token initialize-token-callback help" -f -a "license" -d 'Attach the current registration to a different account using a license key'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and not __fish_seen_subcommand_from show new delete organization devices license token initialize-token-callback help" -f -a "token" -d 'Used internally by callbacks to return tokens as part of registration'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and not __fish_seen_subcommand_from show new delete organization devices license token initialize-token-callback help" -f -a "initialize-token-callback" -d 'Registers the browser token callback without actually registering'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and not __fish_seen_subcommand_from show new delete organization devices license token initialize-token-callback help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from show" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from show" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from new" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from new" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from delete" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from organization" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from organization" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from devices" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from devices" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from license" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from license" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from token" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from token" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from initialize-token-callback" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from initialize-token-callback" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from help" -f -a "show" -d 'Show information about the current registration'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from help" -f -a "new" -d 'Register this client (Must be run before first connection!)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from help" -f -a "delete" -d 'Delete current registration'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from help" -f -a "organization" -d 'Get the name of the current Teams organization'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from help" -f -a "devices" -d 'Display the list of devices associated with the current registration'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from help" -f -a "license" -d 'Attach the current registration to a different account using a license key'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from help" -f -a "token" -d 'Used internally by callbacks to return tokens as part of registration'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from help" -f -a "initialize-token-callback" -d 'Registers the browser token callback without actually registering'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand registration; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand connector; and not __fish_seen_subcommand_from new help" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand connector; and not __fish_seen_subcommand_from new help" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand connector; and not __fish_seen_subcommand_from new help" -f -a "new" -d 'Register a new WARP Connector'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand connector; and not __fish_seen_subcommand_from new help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand connector; and __fish_seen_subcommand_from new" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand connector; and __fish_seen_subcommand_from new" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand connector; and __fish_seen_subcommand_from help" -f -a "new" -d 'Register a new WARP Connector'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand connector; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand settings; and not __fish_seen_subcommand_from list reset support-url mode-switch-allowed help" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand settings; and not __fish_seen_subcommand_from list reset support-url mode-switch-allowed help" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand settings; and not __fish_seen_subcommand_from list reset support-url mode-switch-allowed help" -f -a "list" -d 'Retrieve the current application settings'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand settings; and not __fish_seen_subcommand_from list reset support-url mode-switch-allowed help" -f -a "reset" -d 'Restore settings to default'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand settings; and not __fish_seen_subcommand_from list reset support-url mode-switch-allowed help" -f -a "support-url" -d 'Get the support url for the current Teams organization'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand settings; and not __fish_seen_subcommand_from list reset support-url mode-switch-allowed help" -f -a "mode-switch-allowed" -d 'Outputs true if Teams users should be able to change connection mode, or false if not'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand settings; and not __fish_seen_subcommand_from list reset support-url mode-switch-allowed help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand settings; and __fish_seen_subcommand_from list" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand settings; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand settings; and __fish_seen_subcommand_from reset" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand settings; and __fish_seen_subcommand_from reset" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand settings; and __fish_seen_subcommand_from support-url" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand settings; and __fish_seen_subcommand_from support-url" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand settings; and __fish_seen_subcommand_from mode-switch-allowed" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand settings; and __fish_seen_subcommand_from mode-switch-allowed" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand settings; and __fish_seen_subcommand_from help" -f -a "list" -d 'Retrieve the current application settings'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand settings; and __fish_seen_subcommand_from help" -f -a "reset" -d 'Restore settings to default'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand settings; and __fish_seen_subcommand_from help" -f -a "support-url" -d 'Get the support url for the current Teams organization'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand settings; and __fish_seen_subcommand_from help" -f -a "mode-switch-allowed" -d 'Outputs true if Teams users should be able to change connection mode, or false if not'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand settings; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand status" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand status" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand target; and not __fish_seen_subcommand_from list help" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand target; and not __fish_seen_subcommand_from list help" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand target; and not __fish_seen_subcommand_from list help" -f -a "list" -d 'List all available targets accessible by the current user'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand target; and not __fish_seen_subcommand_from list help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand target; and __fish_seen_subcommand_from list" -s a -l attribute -d 'Filter targets that matches exactly the attribute key and comma-separated values specified' -r
complete -c warp-cli -n "__fish_warp_cli_using_subcommand target; and __fish_seen_subcommand_from list" -s i -l id -d 'Filter targets that matches any of the ID(s)' -r
complete -c warp-cli -n "__fish_warp_cli_using_subcommand target; and __fish_seen_subcommand_from list" -l ip -d 'Filter targets whose IPv4 or IPv6 exactly matches the value provided' -r
complete -c warp-cli -n "__fish_warp_cli_using_subcommand target; and __fish_seen_subcommand_from list" -l ip-begins -d 'Filter targets whose IPv4 or IPv6 addresses begin with the value provided' -r
complete -c warp-cli -n "__fish_warp_cli_using_subcommand target; and __fish_seen_subcommand_from list" -s p -l protocol -d 'Filter targets that matches any of the protocol(s)' -r
complete -c warp-cli -n "__fish_warp_cli_using_subcommand target; and __fish_seen_subcommand_from list" -s u -l username -d 'Filter targets that matches any of the username(s)' -r
complete -c warp-cli -n "__fish_warp_cli_using_subcommand target; and __fish_seen_subcommand_from list" -s n -l vnet -d 'Filter targets that matches any of the VNet(s). VNet names are case-sensitive' -r
complete -c warp-cli -n "__fish_warp_cli_using_subcommand target; and __fish_seen_subcommand_from list" -l max-items -d 'Maximum items to fetch. If `--no-paginate` is present, it takes precedence' -r
complete -c warp-cli -n "__fish_warp_cli_using_subcommand target; and __fish_seen_subcommand_from list" -l page-id -d 'Pagination ID received from last call' -r
complete -c warp-cli -n "__fish_warp_cli_using_subcommand target; and __fish_seen_subcommand_from list" -l per-page -d 'Maximum results to include per page' -r
complete -c warp-cli -n "__fish_warp_cli_using_subcommand target; and __fish_seen_subcommand_from list" -l desc -d 'Order targets in descending order by port'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand target; and __fish_seen_subcommand_from list" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand target; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand target; and __fish_seen_subcommand_from help" -f -a "list" -d 'List all available targets accessible by the current user'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand target; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand trusted; and not __fish_seen_subcommand_from ssid ethernet wifi help" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand trusted; and not __fish_seen_subcommand_from ssid ethernet wifi help" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand trusted; and not __fish_seen_subcommand_from ssid ethernet wifi help" -f -a "ssid" -d 'Configure trusted Wi-Fi networks for which the client will be automatically disconnected'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand trusted; and not __fish_seen_subcommand_from ssid ethernet wifi help" -f -a "ethernet" -d 'Automatically disconnect on all ethernet networks (disabled for Zero Trust customers)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand trusted; and not __fish_seen_subcommand_from ssid ethernet wifi help" -f -a "wifi" -d 'Automatically disconnect on all Wi-Fi networks (disabled for Zero Trust customers)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand trusted; and not __fish_seen_subcommand_from ssid ethernet wifi help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand trusted; and __fish_seen_subcommand_from ssid" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand trusted; and __fish_seen_subcommand_from ssid" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand trusted; and __fish_seen_subcommand_from ssid" -f -a "list"
complete -c warp-cli -n "__fish_warp_cli_using_subcommand trusted; and __fish_seen_subcommand_from ssid" -f -a "add"
complete -c warp-cli -n "__fish_warp_cli_using_subcommand trusted; and __fish_seen_subcommand_from ssid" -f -a "remove"
complete -c warp-cli -n "__fish_warp_cli_using_subcommand trusted; and __fish_seen_subcommand_from ssid" -f -a "reset"
complete -c warp-cli -n "__fish_warp_cli_using_subcommand trusted; and __fish_seen_subcommand_from ssid" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand trusted; and __fish_seen_subcommand_from ethernet" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand trusted; and __fish_seen_subcommand_from ethernet" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand trusted; and __fish_seen_subcommand_from wifi" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand trusted; and __fish_seen_subcommand_from wifi" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand trusted; and __fish_seen_subcommand_from help" -f -a "ssid" -d 'Configure trusted Wi-Fi networks for which the client will be automatically disconnected'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand trusted; and __fish_seen_subcommand_from help" -f -a "ethernet" -d 'Automatically disconnect on all ethernet networks (disabled for Zero Trust customers)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand trusted; and __fish_seen_subcommand_from help" -f -a "wifi" -d 'Automatically disconnect on all Wi-Fi networks (disabled for Zero Trust customers)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand trusted; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and not __fish_seen_subcommand_from dump host ip stats rotate-keys endpoint mtu protocol masque-options help" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and not __fish_seen_subcommand_from dump host ip stats rotate-keys endpoint mtu protocol masque-options help" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and not __fish_seen_subcommand_from dump host ip stats rotate-keys endpoint mtu protocol masque-options help" -f -a "dump" -d 'Get split tunnel routing dump. For include-only mode, this shows routes NOT included'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and not __fish_seen_subcommand_from dump host ip stats rotate-keys endpoint mtu protocol masque-options help" -f -a "host" -d 'Configure split tunnel hosts'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and not __fish_seen_subcommand_from dump host ip stats rotate-keys endpoint mtu protocol masque-options help" -f -a "ip" -d 'Configure split tunnel IPs'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and not __fish_seen_subcommand_from dump host ip stats rotate-keys endpoint mtu protocol masque-options help" -f -a "stats" -d 'Retrieve the stats for the current tunnel connection'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and not __fish_seen_subcommand_from dump host ip stats rotate-keys endpoint mtu protocol masque-options help" -f -a "rotate-keys" -d 'Generate a new key-pair, keeping the current registration'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and not __fish_seen_subcommand_from dump host ip stats rotate-keys endpoint mtu protocol masque-options help" -f -a "endpoint" -d 'Force the client to connect to the specified IP:PORT endpoint (Zero Trust customers must run this command as a privileged user)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and not __fish_seen_subcommand_from dump host ip stats rotate-keys endpoint mtu protocol masque-options help" -f -a "mtu" -d 'Set the MTU value of the tunnel'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and not __fish_seen_subcommand_from dump host ip stats rotate-keys endpoint mtu protocol masque-options help" -f -a "protocol" -d 'Modify the preferred tunnel protocol (Consumer only)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and not __fish_seen_subcommand_from dump host ip stats rotate-keys endpoint mtu protocol masque-options help" -f -a "masque-options" -d 'Modify the MASQUE tunnel protocol options (Consumer only)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and not __fish_seen_subcommand_from dump host ip stats rotate-keys endpoint mtu protocol masque-options help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from dump" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from dump" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from host" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from host" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from host" -f -a "list"
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from host" -f -a "add"
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from host" -f -a "remove"
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from host" -f -a "reset"
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from host" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from ip" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from ip" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from ip" -f -a "list" -d 'List IP ranges in the split tunnel configuration'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from ip" -f -a "add" -d 'Add an IP to split tunnel configuration'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from ip" -f -a "remove" -d 'Remove an IP from split tunnel configuration'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from ip" -f -a "add-range" -d 'Add an IP range to split tunnel configuration'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from ip" -f -a "remove-range" -d 'Remove an IP range from split tunnel configuration'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from ip" -f -a "reset" -d 'Reset IP ranges in the split tunnel configuration to default'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from ip" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from stats" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from stats" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from rotate-keys" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from rotate-keys" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from endpoint" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from endpoint" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from endpoint" -f -a "set" -d 'Set an override'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from endpoint" -f -a "reset" -d 'Remove any configured override'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from endpoint" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from mtu" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from mtu" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from mtu" -f -a "set" -d 'Set an override MTU for the tunnel'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from mtu" -f -a "reset" -d 'Remove any configured MTU override on the tunnel'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from mtu" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from protocol" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from protocol" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from protocol" -f -a "set" -d 'Set the preferred tunnel protocol'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from protocol" -f -a "reset" -d 'Reset the preferred tunnel protocol and use the client-provided default'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from protocol" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from masque-options" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from masque-options" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from masque-options" -f -a "set" -d 'Set the preferred MASQUE protocol options'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from masque-options" -f -a "reset" -d 'Reset the preferred MASQUE protocol options and use the client-provided default'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from masque-options" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from help" -f -a "dump" -d 'Get split tunnel routing dump. For include-only mode, this shows routes NOT included'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from help" -f -a "host" -d 'Configure split tunnel hosts'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from help" -f -a "ip" -d 'Configure split tunnel IPs'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from help" -f -a "stats" -d 'Retrieve the stats for the current tunnel connection'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from help" -f -a "rotate-keys" -d 'Generate a new key-pair, keeping the current registration'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from help" -f -a "endpoint" -d 'Force the client to connect to the specified IP:PORT endpoint (Zero Trust customers must run this command as a privileged user)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from help" -f -a "mtu" -d 'Set the MTU value of the tunnel'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from help" -f -a "protocol" -d 'Modify the preferred tunnel protocol (Consumer only)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from help" -f -a "masque-options" -d 'Modify the MASQUE tunnel protocol options (Consumer only)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand tunnel; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand vnet" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand vnet" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand generate-completions" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand generate-completions" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand stats" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand stats" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand certs" -l no-paginate -d 'Disable automatic pagination'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand certs" -s h -l help -d 'Print help'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and not __fish_seen_subcommand_from api connect debug disconnect dns mdm mode override proxy registration connector settings status target trusted tunnel vnet generate-completions stats certs help" -f -a "api" -d 'Allow overriding Cloudflare API address'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and not __fish_seen_subcommand_from api connect debug disconnect dns mdm mode override proxy registration connector settings status target trusted tunnel vnet generate-completions stats certs help" -f -a "connect" -d 'Maintain a connection whenever possible'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and not __fish_seen_subcommand_from api connect debug disconnect dns mdm mode override proxy registration connector settings status target trusted tunnel vnet generate-completions stats certs help" -f -a "debug" -d 'Debugging commands'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and not __fish_seen_subcommand_from api connect debug disconnect dns mdm mode override proxy registration connector settings status target trusted tunnel vnet generate-completions stats certs help" -f -a "disconnect" -d 'Disconnect the client'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and not __fish_seen_subcommand_from api connect debug disconnect dns mdm mode override proxy registration connector settings status target trusted tunnel vnet generate-completions stats certs help" -f -a "dns" -d 'Configure DNS settings'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and not __fish_seen_subcommand_from api connect debug disconnect dns mdm mode override proxy registration connector settings status target trusted tunnel vnet generate-completions stats certs help" -f -a "mdm" -d 'MDM configs'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and not __fish_seen_subcommand_from api connect debug disconnect dns mdm mode override proxy registration connector settings status target trusted tunnel vnet generate-completions stats certs help" -f -a "mode" -d 'Set the client\'s general operating mode'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and not __fish_seen_subcommand_from api connect debug disconnect dns mdm mode override proxy registration connector settings status target trusted tunnel vnet generate-completions stats certs help" -f -a "override" -d 'Allow temporary overrides of administrative settings'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and not __fish_seen_subcommand_from api connect debug disconnect dns mdm mode override proxy registration connector settings status target trusted tunnel vnet generate-completions stats certs help" -f -a "proxy" -d 'Configure proxy mode settings'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and not __fish_seen_subcommand_from api connect debug disconnect dns mdm mode override proxy registration connector settings status target trusted tunnel vnet generate-completions stats certs help" -f -a "registration" -d 'Registration settings'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and not __fish_seen_subcommand_from api connect debug disconnect dns mdm mode override proxy registration connector settings status target trusted tunnel vnet generate-completions stats certs help" -f -a "connector" -d 'Register a WARP Connector'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and not __fish_seen_subcommand_from api connect debug disconnect dns mdm mode override proxy registration connector settings status target trusted tunnel vnet generate-completions stats certs help" -f -a "settings" -d 'Show or alter general application settings'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and not __fish_seen_subcommand_from api connect debug disconnect dns mdm mode override proxy registration connector settings status target trusted tunnel vnet generate-completions stats certs help" -f -a "status" -d 'Return the current connection status'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and not __fish_seen_subcommand_from api connect debug disconnect dns mdm mode override proxy registration connector settings status target trusted tunnel vnet generate-completions stats certs help" -f -a "target" -d 'Manage targets'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and not __fish_seen_subcommand_from api connect debug disconnect dns mdm mode override proxy registration connector settings status target trusted tunnel vnet generate-completions stats certs help" -f -a "trusted" -d 'Configure trusted networks where the client will be automatically disabled (Consumer only)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and not __fish_seen_subcommand_from api connect debug disconnect dns mdm mode override proxy registration connector settings status target trusted tunnel vnet generate-completions stats certs help" -f -a "tunnel" -d 'Configure tunnel settings'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and not __fish_seen_subcommand_from api connect debug disconnect dns mdm mode override proxy registration connector settings status target trusted tunnel vnet generate-completions stats certs help" -f -a "vnet" -d 'Get or specify connected virtual network'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and not __fish_seen_subcommand_from api connect debug disconnect dns mdm mode override proxy registration connector settings status target trusted tunnel vnet generate-completions stats certs help" -f -a "generate-completions" -d 'Generate completions for a given shell and print to stdout'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and not __fish_seen_subcommand_from api connect debug disconnect dns mdm mode override proxy registration connector settings status target trusted tunnel vnet generate-completions stats certs help" -f -a "stats" -d 'Display statistics for Cloudflare WARP'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and not __fish_seen_subcommand_from api connect debug disconnect dns mdm mode override proxy registration connector settings status target trusted tunnel vnet generate-completions stats certs help" -f -a "certs" -d 'Print all account certificates installed on the device to stdout'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and not __fish_seen_subcommand_from api connect debug disconnect dns mdm mode override proxy registration connector settings status target trusted tunnel vnet generate-completions stats certs help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from api" -f -a "endpoint" -d 'Set an override endpoint for the WARP API'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from debug" -f -a "access-reauth" -d 'Force refresh authentication with Cloudflare Access'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from debug" -f -a "alternate-network" -d 'Get the name of the currently detected alternate network, if any'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from debug" -f -a "connectivity-check" -d 'Enable or disable connectivity checks'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from debug" -f -a "dex" -d 'Get the most recently uploaded DEX data. Returns the most recent test for each dex metric'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from debug" -f -a "network" -d 'Display the current network information'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from debug" -f -a "panic" -d 'Force a daemon panic'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from debug" -f -a "posture" -d 'Display the most recent device posture information'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from debug" -f -a "pcap" -d 'Run a packet capture on the device'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from debug" -f -a "task-dump" -d 'Get a dump of the currently running async tasks'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from debug" -f -a "qlog" -d 'Enable qlog logging on the tunnel, if supported by the tunnel protocol'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from debug" -f -a "log-filter" -d 'Modify the dynamic log filter using env-filter directives'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from dns" -f -a "endpoint" -d 'Configure a custom DNS Over HTTPS server endpoint'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from dns" -f -a "fallback" -d 'Configure fallback domains'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from dns" -f -a "families" -d 'Configure Families Mode settings (Consumer only)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from dns" -f -a "gateway-id" -d 'Force the app to use the specified Gateway ID for DNS queries'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from dns" -f -a "log" -d 'Enable/Disable DNS logging'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from dns" -f -a "stats" -d 'Retrieve DNS stats for the current connection'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from dns" -f -a "default-fallbacks" -d 'Display which DNS servers are being used for default fallback'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from mdm" -f -a "get-configs" -d 'Show information about current MDM configurations'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from mdm" -f -a "set-config" -d 'Apply config from configs found in MDM file'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from override" -f -a "show" -d 'Return information about any currently applied administrative override'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from override" -f -a "unlock" -d 'Temporarily override policies that require the client to stay enabled'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from override" -f -a "generate" -d 'Generate admin override code for Teams account (requires admin permissions)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from override" -f -a "local-network" -d 'Override settings to access the local area network'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from proxy" -f -a "port" -d 'Override the listening port for proxy mode (127.0.0.1:{port})'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from registration" -f -a "show" -d 'Show information about the current registration'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from registration" -f -a "new" -d 'Register this client (Must be run before first connection!)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from registration" -f -a "delete" -d 'Delete current registration'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from registration" -f -a "organization" -d 'Get the name of the current Teams organization'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from registration" -f -a "devices" -d 'Display the list of devices associated with the current registration'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from registration" -f -a "license" -d 'Attach the current registration to a different account using a license key'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from registration" -f -a "token" -d 'Used internally by callbacks to return tokens as part of registration'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from registration" -f -a "initialize-token-callback" -d 'Registers the browser token callback without actually registering'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from connector" -f -a "new" -d 'Register a new WARP Connector'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from settings" -f -a "list" -d 'Retrieve the current application settings'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from settings" -f -a "reset" -d 'Restore settings to default'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from settings" -f -a "support-url" -d 'Get the support url for the current Teams organization'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from settings" -f -a "mode-switch-allowed" -d 'Outputs true if Teams users should be able to change connection mode, or false if not'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from target" -f -a "list" -d 'List all available targets accessible by the current user'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from trusted" -f -a "ssid" -d 'Configure trusted Wi-Fi networks for which the client will be automatically disconnected'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from trusted" -f -a "ethernet" -d 'Automatically disconnect on all ethernet networks (disabled for Zero Trust customers)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from trusted" -f -a "wifi" -d 'Automatically disconnect on all Wi-Fi networks (disabled for Zero Trust customers)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from tunnel" -f -a "dump" -d 'Get split tunnel routing dump. For include-only mode, this shows routes NOT included'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from tunnel" -f -a "host" -d 'Configure split tunnel hosts'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from tunnel" -f -a "ip" -d 'Configure split tunnel IPs'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from tunnel" -f -a "stats" -d 'Retrieve the stats for the current tunnel connection'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from tunnel" -f -a "rotate-keys" -d 'Generate a new key-pair, keeping the current registration'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from tunnel" -f -a "endpoint" -d 'Force the client to connect to the specified IP:PORT endpoint (Zero Trust customers must run this command as a privileged user)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from tunnel" -f -a "mtu" -d 'Set the MTU value of the tunnel'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from tunnel" -f -a "protocol" -d 'Modify the preferred tunnel protocol (Consumer only)'
complete -c warp-cli -n "__fish_warp_cli_using_subcommand help; and __fish_seen_subcommand_from tunnel" -f -a "masque-options" -d 'Modify the MASQUE tunnel protocol options (Consumer only)'
