backend = "glx";

corner-radius = 16.0;
round-borders = 1

blur: 
{
    method = "dual_kawase";
    strength = 8;
    background = false;
    background-frame = false;
    background-fixed = false;
};
