backend = "glx";
corner-radius = 13.0;
rounded-corners-exclude = {
#    "class_g = 'brave'",
}
blur: {
    method = "dual_kawase";
    strength = 50;
    background = false;
    background-frame = false;
    background-fixed = false;
}
