###     Shadows     ###
shadow = true;
shadow-radius = 16;

### Rounded Corners ###
corner-radius = 16.0;
round-borders = 1;

###      Blur       ###

# needed for blur
backend = "glx";

blur: 
{
    method = "dual_kawase";
    strength = 12;
    background = false;
    background-frame = false;
    background-fixed = false;
};
